basesite/urls.py
from django.urls import path

from . import views

app_name = 'basesite'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('success/', views.successView, name='success'),
]

erwebapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basesite.urls')),
    path('', include('projects.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, documentroot=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, documentroot=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('ourwork/', views.ProjectListView.as_view(), name='ourwork'),
    path('ourwork/<int:pk>/', views.ProjectDetailView.as_view(), name='detail'),
]

basesite/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models


class Project(models.Model):
    thumb_image = models.ImageField(upload_to='img', null = True)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return self.title

class Image(models.Model):
    image = models.ImageField(upload_to='img', null = True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    
#class TimeLine(models.Model):
#    project = models.ForeignKey(Project, on_delete=models.CASCADE)

#class Note(models.Model):
#    project = models.ForeignKey(Project, on_delete=models.CASCADE)
#    author = models.CharField(max_length=100)
#    date = models.DateTimeField('date written')
#    note = models.CharField(max_length=2000)

basesite/forms.py
from django import forms


class ContactForm(forms.Form):
    your_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)
    

basesite/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm


def home(request):
    return render(request, 'basesite/home.html')

def about(request):
    return render(request, 'basesite/about.html')

def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            your_email = form.cleaned_data['your_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, your_email, ['admin@emberruby.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('basesite:success')
    return render(request, "basesite/contact.html", {'form': form})
    
def successView(request):
    return HttpResponse('Success! Thank you for your message.')

projects/views.py
#from django.shortcuts import render
from django.views import generic

from . import models


class ProjectListView(generic.ListView):
    model = models.Project
    queryset = models.Project.objects.all()
    template_name = 'projects/ourwork.html'
    
    

class ProjectDetailView(generic.DetailView):
    model = models.Project
    template_name = 'projects/project.html'
     
#def ourwork(request):
#    render(request, 'projects/ourwork.html')

basesite/templates/basesite/about.html
{% extends "basesite/base.html" %}
{% load static %}

{% block nav-about %}"nav-item active"{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    </br>
    </br>
    </br>
    <h1 class="display-3">The Face of Ember Ruby</h1>
    <p>
      After losing our daughter Ember-Ruby to a premmature birth, we were motivated and determined to carry on her memory through our passion for design and archetecture. We now focus our skills and education into helping others, and want to make this Ember Design’s mission.
    </p>
  </div>
</div>

<div class="container">
  <div class="card-deck">
    <div class="card h-100">
      <img class="card-img-top" src="{% static 'basesite/images/reuben.jpg' %}">
      <div class="card-body">
	<h4 class="card-title">Reuben Munro</h4>
	<p class="card-text">
	  Reuben has spent the last 4 years creating high quality rendered 3d plans for design and architecture companies on varying projects from kitchens to public event venues.
	</p>
      </div>
    </div>
    <div class="card">
      <img class="card-img-top" src="{% static 'basesite/images/calita.jpg' %}">
      <div class="card-body">
	<h4 class="card-title">Calita Munro</h4>
	<p class="card-text">
	  Spending years as an artist and creating award winning pieces, Calita brings her extensive knowledge and skills along with her degree in Visual Arts and Design.
	</p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

basesite/templates/basesite/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'basesite/style.css' %}">
    
    <title>Ember Ruby Design</title>
  </head>
  
  <body>
    <header>
      <!-- The navigation bar -->
      {% block nav %}
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
	<a class="navbar-brand">
	  <img src="{% static 'basesite/images/erlogo.jpg' %}" alt="logo" class="rounded" style="width:70px;">
	</a>
	<a class="navbar-brand" href="#">Ember Ruby Design</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
	  <span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse text-right" id="navbarCollapse">
	  <ul class="navbar-nav ml-auto">
	    <!--  Blocks are to set the nav-item to active on the respective html template -->
	    <li class={% block nav-home %}"nav-item"{% endblock %}>
	      <a class="nav-link" href="{% url 'basesite:home' %}">Home</a>
	    </li>
	    <li class={% block nav-about %}"nav-item"{% endblock %}>
	      <a class="nav-link" href="{% url 'basesite:about' %}">About</a>
	    </li>
	    <li class={% block nav-ourwork %}"nav-item"{% endblock %}>
	      <a class="nav-link" href="{% url 'projects:ourwork' %}">Our Work</a>
	    </li>
	    <li class={% block nav-contact %}"nav-item"{% endblock %}>
	      <a class="nav-link" href="{% url 'basesite:contact' %}">Contact</a>
	    </li>
	  </ul>
	</div>
      </nav>
      {% endblock %}
    </header>

    <!-- This is where the content for each page goes -->
    <main role="main">
      {% block content %} {% endblock %}
      </br>
      </br>
    </main>

    <!-- The page footer -->
    <footer class="jumbotron">
      <div class="container">
	<p>Ember Ruby Design 2018</p>
      </div>
    </footer>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

basesite/templates/basesite/contact.html
{% extends "basesite/base.html" %}
{% load static %}

{% block nav-contact %}"nav-item active"{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    </br>
    </br>
    </br>
    <h1>Contact us</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <!-- Email form -->
    <div class="col-md-5">
      <legend>Send us a message</legend>
      <form method="post">
	{% csrf_token %}
	{% for field in form %}
	<div class="form-group">
	  <label class="control-label">{{ field.label }}</label>
	  <input type="text" class="form-control" id="id_{{ field.name }}" name="{{ field.name }}">
	</div>
	{% endfor %}
	<div class="form-actions">
	  <button type="submit" class="btn btn-primary">Send</button>
	</div>
      </form>
<!--
      <form action="">
	<div class="form-group">
	  <label for"name">Your name:</label>
	  <input type="name" class="form-control" id="name">
	</div>
	<div class="form-group">
	  <label for="email">Email address:</label>
	  <input type="email" class="form-control" id="email">
	</div>
	<div class="form-group">
	  <label for="message">Your message</label>
	  <textarea class="form-control" id="message" rows="8"></textarea>
	</div>
	<button type="submit" class="btn btn-primary">Submit</button>
      </form>
-->

    </div>
    <!-- Spacer for smaller screen resolutions -->
    <div class="col-md-2">
</br>
</br>
    </div>
    <!-- Contact details and map -->
    <div class="col-md-5">
      <form>
	<legend>Our office</legend>
	<address>
	  <strong>Ember Ruby Design</strong>
	  </br>
	  1 Imaginary Lane
	  </br>
	  Nelson
	  </br>
	  NEW ZEALAND
	  </br>
	  5000
	</address>
	<address>
	  <strong>Phone</strong>
	  </br>
	  <a href="tel:555-555-5555">(555) 555-5555</a>
	</address>
	<address>
	  <strong>Email</strong>
	  </br>
	  <a href="mailto:info@emberruby.com">info@emberruby.com</a>
	</address>
      </form>
    </div>
  </div>
</div>
{% endblock %}

basesite/templates/basesite/home.html
{% extends "basesite/base.html" %}
{% load static %}

<!-- Sets the nav-item "home" to active -->
{% block nav-home %}"nav-item active"{% endblock %}

{% block content %}
<!-- The first section of the home page -->
<div class="jumbotron">
  <div class="container">
    </br>
    </br>
    </br>
    <p>
      Provider of interior design solutions, layouts and styling.
      Allowing clients to express their ideas and personality through customised design.
    </p>
    <p>
      <a class="btn btn-primary tn-lg" href="#" role="button">View Our Work</a>
    </p>
  </div>
</div>
<!-- The second section of the home page -->
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <p><img class="img-fluid rounded" src="{% static 'basesite/images/consultation.jpg' %}"></p>
      <h2>Consultation</h2>
      <p>
	"With you from the beginning, we offer face to face consultations or video calling online. We start with the basics and go from there."
      </p>
    </div>
    <div class="col-md-3">
      <p><img class="img-fluid rounded" src="{% static 'basesite/images/design.jpg' %}"></p>
      <h2>Design</h2>
      <p>
	"Years of design experience paired with your input, all goes into creating a space you can call your own."
      </p>
    </div>
    <div class="col-md-3">
      <p><img class="img-fluid rounded" src="{% static 'basesite/images/documentation.jpg' %}"></p>
      <h2>Documentation</h2>
      <p>
	"Every idea, draft, sketch and design element documented and crafted in computer software so you can see what stage your project is at and be involved in the whole process. Our clients receive plans, elevations, item lists and high quality renders."
      </p>
    </div>
    <div class="col-md-3">
      <p><img class="img-fluid rounded" src="{% static 'basesite/images/construction.jpg' %}"></p>
      <h2>Construction</h2>
      <p>
	"Right until the end we are there with you ensuring that your project is complete to a high standard and the vision you planned with us."
      </p>
    </div>
  </div>
</div>
{% endblock %}

projects/templates/projects/ourwork.html
{% extends "basesite/base.html" %}
{% load static %}

{% block nav-ourwork %}"nav-item active"{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    </br>
    </br>
    </br>
    <h1>Our Work</h1>
  </div>
</div>

<div class="container">
  <div class="card-deck mh-30">
    {% for project in object_list %}
    <div class="card">
      <img class="card-img-top" src="{{ project.thumb_image }}">
      <div class="card-img-overlay">
	<h4 class="card-title">{{ project.title }}</h4>
	<p class="card-text">
	  {{ project.description }}
	</p>
      </div>
    </div>
    {% empty %}
    <p> No projects yet. </p>
    {% endfor %}
  </div>
</div>

{% endblock %}

projects/templates/projects/project.html
{% extends "basesite/base.html" %}
{% load static %}

{% block nav-ourwork %}"nav-item active"{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    </br>
    </br>
    </br>
    <h1>Our Work</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <!-- Email form -->
    <div class="col-md-5">
      <legend>Send us a message</legend>
    </div>
    <!-- Spacer for smaller screen resolutions -->
    <div class="col-md-2">
</br>
</br>
    </div>
    <!-- Contact details and map -->
    <div class="col-md-5">
	<legend>Our office</legend>
    </div>
  </div>
</div>
{% endblock %}